### ISSUE TITLE
Guys I tried running it and I get this

### ISSUE THREAD

**Issue by imjusttheko** [encryptable/PiratesOfTheCarribeanOnline#5]
http://paste.pound-python.org/show/seJYzLmSCTmiwaqT6Ezb/ 

Username: c
==============================
Starting Pirates Online...
Python: C:/Panda3D-1.9.0/python/ppython.exe
Username: c
Gameserver: 127.0.0.1
==============================
OTPLocalizer: Running in language: english
from otp.otpbase.OTPLocalizerEnglish import *
Traceback (most recent call last):
  File "C:\Panda3D-1.9.0\python\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Panda3D-1.9.0\python\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\Avery\Desktop\Pirates Online\Extracted\PiratesOfTheCarribeanOnline-master\PiratesOfTheCarribeanOnline-master\pirates\piratesbase\PiratesStart.py", line 3, in <module>
    import PiratesPreloader
  File "pirates\piratesbase\PiratesPreloader.py", line 4, in <module>
    import PiratesGlobals
  File "pirates\piratesbase\PiratesGlobals.py", line 5, in <module>
    import PLocalizer
  File "pirates\piratesbase\PLocalizer.py", line 1, in <module>
    from pirates.piratesbase.PLocalizerEnglish import *
  File "pirates\piratesbase\PLocalizerEnglish.py", line 22, in <module>
    from pirates.piratesbase import EmoteGlobals
  File "pirates\piratesbase\EmoteGlobals.py", line 10, in <module>
    from pirates.quest.QuestPrereq import *
  File "pirates\quest\QuestPrereq.py", line 1, in <module>
    from direct.showbase.PythonUtil import POD, makeTuple
ImportError: cannot import name POD
Press any key to continue . . .
 

Please help

**Comment by Puggyblue999** [comment]
I get the same error, it's probably that POD must be removed in newer Panda3D versions.

**Comment by imjusttheko** [comment]
Then which one should i use

**Comment by encryptable** [comment]
@imjusttheko Download the panda located [here.](https://github.com/toontownfellowship/ThirdParty/blob/master/windows/Panda3D-1.9.0.exe?raw=true)

**Comment by imjusttheko** [comment]
Use this 
https://github.com/toontownfellowship/ThirdParty/blob/master/windows/Panda3D-1.9.0.exe?raw=true
